In [181]:
import torch
from torch import nn
from torch.nn import functional as F
from torch.nn.parameter import Parameter
import tensorflow as tf
torch.__version__, tf.__version__

('1.5.0', '2.2.0')

In [11]:
tf.constant(1, dtype=tf.float32), tf.constant(1, dtype=tf.float32).shape

(<tf.Tensor: shape=(), dtype=float32, numpy=1.0>, TensorShape([]))

In [10]:
torch.tensor(2, dtype=torch.float32), torch.tensor(2, dtype=torch.float32).shape

(tensor(2.), torch.Size([]))

In [15]:
tf.ones([1, 10], dtype=tf.float32), tf.ones([1, 10], dtype=tf.float32).shape

(<tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>,
 TensorShape([1, 10]))

In [16]:
torch.ones((1,10), dtype=torch.float32), torch.ones((1,10), dtype=torch.float32).shape

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]), torch.Size([1, 10]))

In [46]:
a = tf.math.log(tf.constant([[0.2, 0.5, 1, 5]]) + tf.constant(1.0))
b = tf.math.divide(tf.constant(1.0), a)
c = tf.ones([1, 4], tf.float32)
b.shape, tf.ones([1, 4]).shape
tf.matmul(b, tf.ones([4, 1]))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[9.951922]], dtype=float32)>

In [50]:
a = torch.log(torch.tensor([[0.2, 0.5, 1, 5]]) + torch.tensor(1, dtype=torch.float32))
b = torch.div(torch.tensor(1, dtype=torch.float32), a)
c = torch.ones((4,1), dtype=torch.float32)
b @ c, torch.matmul(b, c)

(tensor([[9.9519]]), tensor([[9.9519]]))

In [52]:
Parameter(torch.Tensor(2, 2))

Parameter containing:
tensor([[0.1823, 0.4055],
        [0.6931, 1.7918]], requires_grad=True)

In [61]:
a = torch.rand((2,3,1))
b = torch.rand((2,3,4))
print(a, b)

c = torch.cat((a, b), dim=2)
print(c)

for t in range(3):
    print("index: ", t)
    print(c[:, t, :])
#     print(c[:, t, 0])
#     print(c[:, t, 1:])

tensor([[[0.6647],
         [0.1582],
         [0.0415]],

        [[0.3778],
         [0.9922],
         [0.2763]]]) tensor([[[0.5134, 0.9242, 0.4529, 0.6371],
         [0.4035, 0.0728, 0.4480, 0.2958],
         [0.9435, 0.3630, 0.8144, 0.9952]],

        [[0.9117, 0.9150, 0.2996, 0.6063],
         [0.3567, 0.9934, 0.8267, 0.9316],
         [0.4794, 0.6481, 0.3292, 0.1876]]])
tensor([[[0.6647, 0.5134, 0.9242, 0.4529, 0.6371],
         [0.1582, 0.4035, 0.0728, 0.4480, 0.2958],
         [0.0415, 0.9435, 0.3630, 0.8144, 0.9952]],

        [[0.3778, 0.9117, 0.9150, 0.2996, 0.6063],
         [0.9922, 0.3567, 0.9934, 0.8267, 0.9316],
         [0.2763, 0.4794, 0.6481, 0.3292, 0.1876]]])
index:  0
tensor([[0.6647, 0.5134, 0.9242, 0.4529, 0.6371],
        [0.3778, 0.9117, 0.9150, 0.2996, 0.6063]])
index:  1
tensor([[0.1582, 0.4035, 0.0728, 0.4480, 0.2958],
        [0.9922, 0.3567, 0.9934, 0.8267, 0.9316]])
index:  2
tensor([[0.0415, 0.9435, 0.3630, 0.8144, 0.9952],
        [0.2763, 0.4794, 0.6

In [65]:
tf.multiply(a, b)

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0.3412673 , 0.6143132 , 0.30103528, 0.42347988],
        [0.06384967, 0.01151462, 0.07089078, 0.04680625],
        [0.03913313, 0.01505405, 0.03377762, 0.04127943]],

       [[0.34445944, 0.3457046 , 0.11317814, 0.22907218],
        [0.35396236, 0.98564976, 0.82023317, 0.9243021 ],
        [0.13246745, 0.17909516, 0.09095483, 0.05182858]]], dtype=float32)>

In [67]:
torch.mul(a, b)

tensor([[[0.3413, 0.6143, 0.3010, 0.4235],
         [0.0638, 0.0115, 0.0709, 0.0468],
         [0.0391, 0.0151, 0.0338, 0.0413]],

        [[0.3445, 0.3457, 0.1132, 0.2291],
         [0.3540, 0.9856, 0.8202, 0.9243],
         [0.1325, 0.1791, 0.0910, 0.0518]]])

In [73]:
print(b.shape, b)
bu = torch.unsqueeze(b, 0)
bu.shape, bu

torch.Size([2, 3, 4]) tensor([[[0.5134, 0.9242, 0.4529, 0.6371],
         [0.4035, 0.0728, 0.4480, 0.2958],
         [0.9435, 0.3630, 0.8144, 0.9952]],

        [[0.9117, 0.9150, 0.2996, 0.6063],
         [0.3567, 0.9934, 0.8267, 0.9316],
         [0.4794, 0.6481, 0.3292, 0.1876]]])


(torch.Size([1, 2, 3, 4]),
 tensor([[[[0.5134, 0.9242, 0.4529, 0.6371],
           [0.4035, 0.0728, 0.4480, 0.2958],
           [0.9435, 0.3630, 0.8144, 0.9952]],
 
          [[0.9117, 0.9150, 0.2996, 0.6063],
           [0.3567, 0.9934, 0.8267, 0.9316],
           [0.4794, 0.6481, 0.3292, 0.1876]]]]))

In [75]:
buc = torch.cat([bu, bu], 0)
buc.shape, buc

(torch.Size([2, 2, 3, 4]),
 tensor([[[[0.5134, 0.9242, 0.4529, 0.6371],
           [0.4035, 0.0728, 0.4480, 0.2958],
           [0.9435, 0.3630, 0.8144, 0.9952]],
 
          [[0.9117, 0.9150, 0.2996, 0.6063],
           [0.3567, 0.9934, 0.8267, 0.9316],
           [0.4794, 0.6481, 0.3292, 0.1876]]],
 
 
         [[[0.5134, 0.9242, 0.4529, 0.6371],
           [0.4035, 0.0728, 0.4480, 0.2958],
           [0.9435, 0.3630, 0.8144, 0.9952]],
 
          [[0.9117, 0.9150, 0.2996, 0.6063],
           [0.3567, 0.9934, 0.8267, 0.9316],
           [0.4794, 0.6481, 0.3292, 0.1876]]]]))

In [79]:
buc.transpose(0, 1).contiguous()

tensor([[[[0.5134, 0.9242, 0.4529, 0.6371],
          [0.4035, 0.0728, 0.4480, 0.2958],
          [0.9435, 0.3630, 0.8144, 0.9952]],

         [[0.5134, 0.9242, 0.4529, 0.6371],
          [0.4035, 0.0728, 0.4480, 0.2958],
          [0.9435, 0.3630, 0.8144, 0.9952]]],


        [[[0.9117, 0.9150, 0.2996, 0.6063],
          [0.3567, 0.9934, 0.8267, 0.9316],
          [0.4794, 0.6481, 0.3292, 0.1876]],

         [[0.9117, 0.9150, 0.2996, 0.6063],
          [0.3567, 0.9934, 0.8267, 0.9316],
          [0.4794, 0.6481, 0.3292, 0.1876]]]])

In [67]:
from enum import IntEnum
class Dim(IntEnum):
    batch = 0
    seq = 1
    feature = 2
    
class NaiveLSTM(nn.Module):
    def __init__(self, input_sz: int, hidden_sz: int):
        super().__init__()
        self.input_size = input_sz
        self.hidden_size = hidden_sz
        # input gate
        self.W_ii = Parameter(torch.Tensor(input_sz, hidden_sz))
        self.W_hi = Parameter(torch.Tensor(hidden_sz, hidden_sz))
        self.b_i = Parameter(torch.Tensor(hidden_sz))
        # forget gate
        self.W_if = Parameter(torch.Tensor(input_sz, hidden_sz))
        self.W_hf = Parameter(torch.Tensor(hidden_sz, hidden_sz))
        self.b_f = Parameter(torch.Tensor(hidden_sz))
        # ???
        self.W_ig = Parameter(torch.Tensor(input_sz, hidden_sz))
        self.W_hg = Parameter(torch.Tensor(hidden_sz, hidden_sz))
        self.b_g = Parameter(torch.Tensor(hidden_sz))
        # output gate
        self.W_io = Parameter(torch.Tensor(input_sz, hidden_sz))
        self.W_ho = Parameter(torch.Tensor(hidden_sz, hidden_sz))
        self.b_o = Parameter(torch.Tensor(hidden_sz))
         
        self.init_weights()
     
    def init_weights(self):
        for p in self.parameters():
            if p.data.ndimension() >= 2:
                nn.init.xavier_uniform_(p.data)
            else:
                nn.init.zeros_(p.data)
         
    def forward(self, x: torch.Tensor, init_states=None):
        """Assumes x is of shape (batch, sequence, feature)"""
        bs, seq_sz, _ = x.size()
        hidden_seq = []
        if init_states is None:
            h_t, c_t = torch.zeros(self.hidden_size).to(x.device), torch.zeros(self.hidden_size).to(x.device)
        else:
            h_t, c_t = init_states
        for t in range(seq_sz): # iterate over the time steps
            x_t = x[:, t, :]
            i_t = torch.sigmoid(x_t @ self.W_ii + h_t @ self.W_hi + self.b_i)
            f_t = torch.sigmoid(x_t @ self.W_if + h_t @ self.W_hf + self.b_f)
            g_t = torch.tanh(x_t @ self.W_ig + h_t @ self.W_hg + self.b_g)
            o_t = torch.sigmoid(x_t @ self.W_io + h_t @ self.W_ho + self.b_o)
            c_t = f_t * c_t + i_t * g_t
            h_t = o_t * torch.tanh(c_t)
            print(h_t.shape)
            print(c_t.shape)
            print(h_t.unsqueeze(Dim.batch).shape)
#             hidden_seq.append(h_t.unsqueeze(Dim.batch))
            
            hidden_seq.append(torch.stack((h_t, c_t)))
            
        hidden_seq = torch.cat(hidden_seq, dim=Dim.batch)
        print(hidden_seq.shape)
        # reshape from shape (sequence, batch, feature) to (batch, sequence, feature)
        hidden_seq = hidden_seq.transpose(Dim.batch, Dim.seq).contiguous()
        return hidden_seq

In [68]:
lstm = NaiveLSTM(4, 4)

In [199]:
# b.shape (2,3,4)
lstm(b), lstm(b).shape,  lstm(b)[:, -1, :],  lstm(b)[:, -1, :].shape
# lstm(b)[:, 0, :, :], lstm(b).shape, lstm(b)[:, 0, :, :].shape

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([1, 3, 4])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([1, 3, 4])
torch.Size([4, 3, 4])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([1, 3, 4])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([1, 3, 4])
torch.Size([4, 3, 4])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([1, 3, 4])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([1, 3, 4])
torch.Size([4, 3, 4])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([1, 3, 4])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([1, 3, 4])
torch.Size([4, 3, 4])


(tensor([[[-1.3717e-01,  1.0376e-01,  1.3320e-01, -1.1520e-02],
          [-2.9503e-01,  2.6309e-01,  2.9617e-01, -4.3014e-02],
          [-1.9200e-01,  1.3171e-01,  2.1525e-01, -7.0139e-02],
          [-3.3907e-01,  3.6018e-01,  4.3895e-01, -1.8758e-01]],
 
         [[-3.4174e-03,  1.2078e-01,  1.3161e-01, -4.3694e-02],
          [-6.1657e-03,  3.0510e-01,  2.3214e-01, -1.0799e-01],
          [ 3.7725e-02,  1.2550e-01,  1.1936e-01, -7.3158e-02],
          [ 5.4373e-02,  4.0061e-01,  2.0882e-01, -1.4731e-01]],
 
         [[ 2.9614e-02,  8.8284e-02,  8.3265e-02,  1.4915e-04],
          [ 6.0430e-02,  1.9572e-01,  1.6590e-01,  3.6722e-04],
          [-1.8403e-01,  1.0382e-01,  9.9795e-02,  3.3597e-02],
          [-3.2940e-01,  3.1106e-01,  2.7646e-01,  1.1721e-01]]],
        grad_fn=<CopyBackwards>),
 torch.Size([3, 4, 4]),
 tensor([[-0.3391,  0.3602,  0.4390, -0.1876],
         [ 0.0544,  0.4006,  0.2088, -0.1473],
         [-0.3294,  0.3111,  0.2765,  0.1172]], grad_fn=<SliceBackward>)

In [201]:
torch.argmax(lstm(b)[:, -1, :], 1)

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([1, 3, 4])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([1, 3, 4])
torch.Size([4, 3, 4])


tensor([2, 1, 1], grad_fn=<NotImplemented>)

In [192]:
torch.nn.BCEWithLogitsLoss()(torch.tensor([[0.1, 0.8],[0.3, 0.7]]), torch.tensor([[1,0], [0,1]],dtype=torch.float32))

tensor(0.7683)

In [196]:
class masked_softmax_cross_entropy_loss(nn.Module):
    def __init__(self, weight=None):
        super(masked_softmax_cross_entropy_loss, self).__init__()

    def forward(self, input, target):
        if not target.is_same_size(input):
            raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))

        input = F.softmax(input)
        loss = -torch.sum(target * torch.log(input), 1)
        loss = torch.unsqueeze(loss, 1)
        return loss
    
masked_softmax_cross_entropy_loss()(torch.tensor([[0.1, 0.8],[0.3, 0.7]]), torch.tensor([[1,0], [0,1]]))

/Users/alexgre/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/ipykernel_launcher.py:9: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  if __name__ == '__main__':


tensor([[1.1032],
        [0.5130]])

In [195]:
tf.nn.softmax_cross_entropy_with_logits(labels=[[1,0],[0,1]], logits=[[0.1, 0.8],[0.3, 0.7]])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.1031861, 0.5130153], dtype=float32)>

In [228]:
import torch
from torch.nn.parameter import Parameter
from torch import nn as N
from torch.nn import functional as F
import numpy as np


class TLSTMConfig:
    def __init__(self, input_dim, output_dim, hidden_dim, fc_dim, dropoutput_rate):
        self.dropout_prob = dropoutput_rate
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.hidden_dim = hidden_dim
        self.fc_dim = fc_dim


class SoftmaxCrossEntropyLoss(N.Module):
    """
    equivalent implementation of tf.nn.softmax_cross_entropy_with_logits
    """

    def __init__(self, weight=None):
        super().__init__()

    def forward(self, inputs, targets):
        if not targets.is_same_size(inputs):
            raise ValueError("Target size ({}) must be the same as input size ({})".format(targets.size(),
                                                                                           inputs.size()))

        inputs = F.softmax(inputs)
        loss = -torch.sum(targets * torch.log(inputs), 1)
        loss = torch.unsqueeze(loss, 1)
        return torch.mean(loss)


class TLSTMCell(N.Module):

    def __init__(self, input_dim, hidden_dim):
        super().__init__()
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim

        self.Wi = Parameter(torch.Tensor(input_dim, hidden_dim))
        self.Ui = Parameter(torch.Tensor(hidden_dim, hidden_dim))
        self.bi = Parameter(torch.Tensor(hidden_dim))

        self.Wf = Parameter(torch.Tensor(input_dim, hidden_dim))
        self.Uf = Parameter(torch.Tensor(hidden_dim, hidden_dim))
        self.bf = Parameter(torch.Tensor(hidden_dim))

        self.Wog = Parameter(torch.Tensor(input_dim, hidden_dim))
        self.Uog = Parameter(torch.Tensor(hidden_dim, hidden_dim))
        self.bog = Parameter(torch.Tensor(hidden_dim))

        self.Wc = Parameter(torch.Tensor(input_dim, hidden_dim))
        self.Uc = Parameter(torch.Tensor(hidden_dim, hidden_dim))
        self.bc = Parameter(torch.Tensor(hidden_dim))

        self.W_decomp = Parameter(torch.Tensor(hidden_dim, hidden_dim))
        self.b_decomp = Parameter(torch.Tensor(hidden_dim))

    def init_weights(self):
        for p in self.parameters():
            if p.data.ndimension() >= 2:
                N.init.xavier_uniform_(p.data)
            else:
                N.init.zeros_(p.data)

    def forward(self, x: torch.Tensor, time: torch.Tensor, prev_hidden_state=None):
        # x has three dim: batch size(pats), seq_size(encounters), v_dim(features)
        bz, seq_sz, v_dim = x.size()
        tbz, tseq_sz, tv_dim = time.size()
        assert bz == tbz and seq_sz == tseq_sz, \
            "feature and time seq have different batch size {}-{} or seq len {}-{}".format(bz, tbz, seq_sz, tseq_sz)

        # init hidden if no previous hidden
        if prev_hidden_state is None:
            h_t, c_t = torch.zeros(self.hidden_dim).to(x.device), torch.zeros(self.hidden_dim).to(x.device)
        else:
            h_t, c_t = prev_hidden_state

        # recurrent loop
        hidden_seq = []
        for i, t in enumerate(range(seq_sz)):
            x_t = x[:, t, :]  # (batch, input)
            print(x_t.shape)
            # process time difference
            t_t = time[:, t, :]
            print(t_t.shape)
            T = self.map_elapse_time(t_t)
            print(T.shape)
            C_ST = torch.tanh(torch.matmul(c_t, self.W_decomp) + self.b_decomp)
            C_ST_dis = torch.mul(T, C_ST)
            c_t = c_t - C_ST + C_ST_dis
            print(c_t.shape)
            # input gate
            i_t = torch.sigmoid(torch.matmul(x_t, self.Wi) + torch.matmul(h_t, self.Ui) + self.bi)
            print(i_t.shape)
            # forget gate
            f_t = torch.sigmoid(torch.matmul(x_t, self.Wf) + torch.matmul(h_t, self.Uf) + self.bf)
            print(f_t.shape)
            # output gate
            o_t = torch.sigmoid(torch.matmul(x_t, self.Wog) + torch.matmul(h_t, self.Uog) + self.bog)
            print(o_t.shape)
            # cadidate MemCell
            C = torch.tanh(torch.matmul(x_t, self.Wc) + torch.matmul(h_t, self.Uc) + self.bc)
            print(C.shape)
            # current MemCell
            C_t = f_t * c_t + i_t * C
            # current hidden state
            c_h_t = o_t * torch.tanh(C_t)
            # hidden_seq.append(torch.stack((c_h_t, C_t)))
            hidden_seq.append(c_h_t.unsqueeze(0))  # create extra dim for later concat (seq, batch, input)

        hidden_seq = torch.cat(hidden_seq, dim=0)  # concat to get the seq dim back (seq, batch, input)
        # hidden_seq = hidden_seq.transpose(0, 1).contiguous()  # (seq, batch, input) => (batch, seq, input)
        return hidden_seq, (h_t, c_t)

    def map_elapse_time(self, t):
        c1 = torch.tensor(1, dtype=torch.float32)
        c2 = torch.tensor(np.e, dtype=torch.float32)

        T = torch.div(c1, torch.log(t + c2))
        grid = torch.ones((1, self.hidden_dim), dtype=torch.float32)
        return torch.matmul(T, grid)


class TLSTM(N.Module):

    def __init__(self, config=None):
        super().__init__()
        # self.fc_dim = fc_dim
        # self.output_dim = output_dim
        self.tlstm = TLSTMCell(config.input_dim, config.hidden_dim)
        self.dropout_prob = config.dropout_prob
        self.fc_layer = N.Linear(config.hidden_dim, config.fc_dim)
        self.output_layer = N.Linear(config.fc_dim, config.output_dim)

        # we can use pytorch default implementation of binary loss function - BCEWithLogitsLoss
        # but we found the output did not exactly match the tf.nn.softmax_cross_entropy_with_logits with mean reduce
        # To make sure, results repeatable, we will use SoftmaxCrossEntropyLoss for now
        # self.loss_fct = N.BCEWithLogitsLoss()
        self.loss_fct = SoftmaxCrossEntropyLoss()

    def forward(self, feature, time, labels):
        # get raw logits
        seq, (h_t, c_t) = self.tlstm(feature, time)
        seq = seq[-1, :, :]  # (seq, batch, input); get the last seq for classification
        seq = F.relu(self.fc_layer(seq))
        seq = F.dropout(seq, p=self.dropout_prob)
        logits = self.output_layer(seq)

        # measure loss
        loss = self.loss_fct(logits, labels)
        return loss, logits, torch.argmax(logits, dim=1)

In [229]:
config = TLSTMConfig(4, 2, 10, 5, 0.1)
t = TLSTM(config)
label = torch.tensor([[0,1], [1,0], [0,1]])
x = torch.rand(3,2,1)
print(b)
t(b, , label)

torch.Size([3, 4])
torch.Size([3, 1])
torch.Size([3, 10])
torch.Size([3, 10])
torch.Size([3, 10])
torch.Size([3, 10])
torch.Size([3, 10])
torch.Size([3, 10])
torch.Size([3, 4])
torch.Size([3, 1])
torch.Size([3, 10])
torch.Size([3, 10])
torch.Size([3, 10])
torch.Size([3, 10])
torch.Size([3, 10])
torch.Size([3, 10])


/Users/alexgre/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/ipykernel_launcher.py:30: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


(tensor(0.6366, grad_fn=<MeanBackward0>),
 tensor([[-0.3495,  0.3101],
         [-0.3495,  0.3101],
         [-0.3495,  0.3101]], grad_fn=<AddmmBackward>),
 tensor([1, 1, 1], grad_fn=<NotImplemented>))